### PR TITLE
Build on oldest still-supported distribution

### PR DESCRIPTION
**Pull request by probonopd**
https://github.com/AppImage/appimage.github.io/pull/1009#issuecomment-449602607

Please enable GitHub Issues for the project so that one can communicate without sending a pull request, thanks.

### CODE REVIEW

**Comment by redtide** [comment]
> 
> 
> [AppImage/appimage.github.io#1009 (comment)](https://github.com/AppImage/appimage.github.io/pull/1009#issuecomment-449602607)
> 
> Please enable GitHub Issues for the project so that one can communicate without sending a pull request, thanks.

I have an issue tracker [here on gitlab](https://gitlab.com/azdrums/smarthhc/smarthhc/issues), is it necessary to have one also here for these kind of tasks? Regards.

**Comment by probonopd** [comment]
Thank you very much. Highly appreciated!

**Comment by redtide** [comment]
Sorry but I don't get it, you need a issue tracker here, the one on Gitlab or are you talking about the fix?

**Comment by redtide** [comment]
oh OK, thanks to you too for these amazing tools!

**Pull request closed without merging**
